---

git_repo: git@github.com:evenset/ansible-node.git

application_name: demo


ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDyzCCArOgAwIBAgIJALc5j3PCTfDrMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNV
  BAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UEBwwHVG9yb250bzEVMBMGA1UECgwM
  RXZlbnNldCBJbmMuMRQwEgYDVQQDDAtldmVuc2V0LmNvbTEhMB8GCSqGSIb3DQEJ
  ARYSaGVzYW1kQGV2ZW5zZXQuY29tMB4XDTE3MDYwNTE2MzA0MloXDTE4MDYwNTE2
  MzA0MlowfDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQHDAdUb3Jv
  bnRvMRUwEwYDVQQKDAxFdmVuc2V0IEluYy4xFDASBgNVBAMMC2V2ZW5zZXQuY29t
  MSEwHwYJKoZIhvcNAQkBFhJoZXNhbWRAZXZlbnNldC5jb20wggEiMA0GCSqGSIb3
  DQEBAQUAA4IBDwAwggEKAoIBAQCv7JuyP0iR7VAvqDU9LRn6kNZOHeE4cmsua9rw
  snP9S94QGuAUvllVwP3LF1YnYJgwrOsUOqMreNe3zr+fm5bV+42vBUDEm1YPJ05T
  jBIa83gveAsooJlne+DSN83tp8RnXh/9BhNfJ8cdFghEBto/EEkxp2cI+7u3rEtg
  ZXo4eh6cydPN2zfGJ7jwyZeEM4QLAghagJdquqrsUhfQa0eIMvqIj7HD5brtK0IA
  iHnhDlkk+41FRY5bdlMgTUprfrgTF39dkyHS2BX3Whuy6EnyUylFcspaeuWhA6Lu
  nSItVdpIEnLzijSrWyCHM4n9oGN5RIYeLx17KDtC40ct3F1JAgMBAAGjUDBOMB0G
  A1UdDgQWBBQcbXyg0Y30jE/rxa117kXcVO+/sDAfBgNVHSMEGDAWgBQcbXyg0Y30
  jE/rxa117kXcVO+/sDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB7
  4hQMuctrzHVKQJlEfMkTnb0+t3o0Yl/tPF5cCtdY8Er910/hv4xhDp9bCDd3atAx
  NxXPlMj96Z60WAdMlY6HP2Q2cxFdO3EOzFNssEQi0r6cWNkt1kqSefjj4praL5pF
  jDJLbDsV1jRAnVrFg/GCaM6Ih4+Q4Ta1j/ORvxdz+KH/exfbXqURgHRaH97DNA4S
  RWtgzWgSGCiR77XfzaaEVZUFAnSR50CCuxxCGFgzwxANiiW1gBHEhR/hXCgdQD/2
  wpuYKStMm0g8YJMg9mEdHMzE4FFdoO1Oz7HRcxLXcHOj+3HF67NKG57F5ZhU/kjP
  BMeuHUtI2Qt7LvD8EEhY
  -----END CERTIFICATE-----

# This key is for demo purposes only. Use ansible-vault if you're
# committing your key to the repo

ssl_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCv7JuyP0iR7VAv
  qDU9LRn6kNZOHeE4cmsua9rwsnP9S94QGuAUvllVwP3LF1YnYJgwrOsUOqMreNe3
  zr+fm5bV+42vBUDEm1YPJ05TjBIa83gveAsooJlne+DSN83tp8RnXh/9BhNfJ8cd
  FghEBto/EEkxp2cI+7u3rEtgZXo4eh6cydPN2zfGJ7jwyZeEM4QLAghagJdquqrs
  UhfQa0eIMvqIj7HD5brtK0IAiHnhDlkk+41FRY5bdlMgTUprfrgTF39dkyHS2BX3
  Whuy6EnyUylFcspaeuWhA6LunSItVdpIEnLzijSrWyCHM4n9oGN5RIYeLx17KDtC
  40ct3F1JAgMBAAECggEANlbcRLN9Y+2sbfwD7dCHjLi+KUTbc0cMSjtwVhaY8y1C
  +zCB9IZTK8S/38JmjyUr/ST8O7RdACmEYDcRQ2iYr6HSwrPZrKDadTXL4MyMLxzz
  C56Fu9fXanp+GBC6n+TJKrCNKud8hlDQFPDgPrrrIL2UDi1KCyFOe05RvgW6OcUj
  ozes+Ow/m/lm1J9n3HnHybqAAbP/weDvOlx6p/KhfwnD3O6fhS/UVvHNWYtQA6ku
  TcRa0xpkn0/n1tynKyp/k2D/F2oKK3u6Jji7jUQthDeOkzywhJg5cSRlZ5/uGK2o
  ylCmTpzHZpE+sXbt9vOptukM6gTLf2U6nYxFmsi+jQKBgQDVIHJ/OteFtDFoRtMc
  BZJaHPQ197Dkje21AHrbns23jOrFCiqwXl6Zyp4eejlFohvLxl+B06FvDjB+dh2t
  U7mUtiPZqPpt0t2/BVXQEnkuWS6CYdHlRzESsUM8qiMJUO1UZxrGYSXbHAbBTUJt
  snJ/FIThesCC07I7PsheFWdb+wKBgQDTUFCzhzMwQ+cHM3NvUVW5mT5zS6fh1SQN
  /wQuFnXL9GlrZXMmp7bjVcrjHMenSkA2wWHADaGLv3znVW/EpyVa1N6sd0+GIzy5
  lmh7jm3VUUXm22RyyWYmvT59Qh7YN8GFo4niIDUAcwgSwe7KcrDwFYwpfMadvMlA
  NjLfmPCEiwKBgE6NXgYMzwDlsEwpxoeOeimigFQfzd//e7x5x86IknPziVhEbgWB
  UsbGSk8bZ16F6E7L98mnEdoX1cHWkQugT0dDdqUzxdGSpc5RDhbZqDZwAldl7HHg
  MnMcSJbkcnNtk3vHYLP7fHNsugSnEDPUUKUMEAn3L1tI4Wk6s6kRpH3fAoGAHI0y
  ij9PTEswcQmjpDvSIGSzSnLDeUEKQRXe47dHLUqV39vyRhvNG0RhSHSACXt/16Yj
  ZgaxeCdkYgFqO6D17CLs/1KTnSUvtEe9UEx7TKJRlpK4LMZHlh5lzhjcAAzwifUB
  0VrWrnvccGRhtlruy1GuAYEJeRCkBJgOIaYRgWcCgYB7heDuxYGjd1GY0c8kQSec
  hEPhDefzUhOJP3i+YnFGz0qyP6J6ld069M0giixM1xJI3je0KEM42CDYcw6kGC2D
  cGE0X7dFEvO8XNDlV35cI88f6jwVMTKbOOOM/BEjGf6YrheYxhXjI/DIZ3BqztuG
  GBZB8tJxofkwZ4EYG/4ZFw==
  -----END PRIVATE KEY-----