---
- include: install_node.yml
  tags: packages
  become_user: root

- include: create_users_and_groups.yml
  become_user: root

- include: set_file_permissions.yml
  tags: deploy
  become_user: root

